# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               DISCOVER Cookbook
tagline:             'Diverse & Inclusive Spaces and Conferences'
description:         'The NumFOCUS DISCOVER Cookbook'
url:                 https://discover-cookbook.github.io/
giturl:              https://github.com/discover-cookbook/discover-cookbook.github.io
baseurl:             / 
paginate:            5

# Custom vars
version:             0.0.1

github.repo: https://github.com/discover-cookbook/discover-cookbook.github.io
